### ISSUE TITLE
This is so exciting , thank you , but I seem to be just falling short....

### ISSUE THREAD

**Issue by Osymoko** [GerryDazoo/Slinger#2]
Hi , I have tried a few variants with the windows.exe but am getting an error log.

This maybe because  I am not sure of the SB350 password, from the attached shot I think it should be 0369 (with no quotation marks) but there a lots of other passwords as well?  I do have two SB350s but the second one is currently switched off so should not be interfering.

I have attached the logs, config and port forwarding proof as well to see it I have missed anything,  Thank you so much again for this - it's wonderful
![SBpass](https://user-images.githubusercontent.com/108595850/177056454-5e94f0fe-1317-40f5-8d08-c25801aa61a3.JPG)
![Config](https://user-images.githubusercontent.com/108595850/177056459-a7e0da6a-c0b0-4a79-bcf3-532e9d890348.JPG)
![log](https://user-images.githubusercontent.com/108595850/177056466-d1b5b57b-89a8-4faa-b434-f80a6a61f942.JPG)
![VLC](
![portforward](https://user-images.githubusercontent.com/108595850/177056490-ba21fb4a-857e-482b-8d51-c9d9bdd3600d.JPG)
https://user-images.githubusercontent.com/108595850/177056477-2d7f8970-36c8-4b7b-9213-0435a386a40f.jpg)
.

**Comment by GerryDazoo** [comment]
Thanks for trying this out. Three things, based on your slingbox info please try the admin password that starts with "4VPD....".
Also can you make sure your using the latest version of the code. I would have expected that you show have received an error message saying to check your password.
Finally there should be no space after the = sign and the password in your config.ini. When I get a chance I'll add some code to allow for this.

**Comment by Osymoko** [comment]
Hi Gerry, 

Thanks for such prompt response.  I have updated to May 21 code and  tried the automatic search but it does not find either of my boxes on the network ( I have tested each separately, switched one off, left both on , but same failure message')..
![image](https://user-images.githubusercontent.com/108595850/177202494-4605151d-119c-47d4-b15b-eb6a38ba0983.png)

we have checked the SB350 address:

![SBportdetials](https://user-images.githubusercontent.com/108595850/177202968-f1361eea-f0ff-4f06-93df-071aecd412e3.JPG)

..and hence I have updated the congfig and password (using no quotation marks or spaces) so it reads:
![image](https://user-images.githubusercontent.com/108595850/177202864-7157af7c-0b22-4d97-a839-5254f9659b33.png)

but still get the error unfortunately when using "http://192.168.1.116:8080/slingbox"
![image](https://user-images.githubusercontent.com/108595850/177203295-3511cac3-06f3-409e-b0fb-68e564f972e8.png)

 Anything you can spot would be amazing thank you ..

Many thanks indeed
 
Gary

**Comment by GerryDazoo** [comment]
Gary,
You've gotten past getting logged into the box. Yeah! But it is failing when trying to configure the video stream. Can you verify that there is a video signal? I've only been able to test with my 500 box, so there may be something special about the default video parameters I've selected. Can you try a different video resolution=5 (VGA 640x480)  instead of the 1280x720 default. you may also want to change the videobandwidth=2000. BTW what is your video source?
- Gerry

I'm waiting on a couple older slingboxes to test with. I might be able to reproduce your issue with one of them ( assuming we can't get it going soon) but it will be next week sometime before I can get home to do some more testing.

**Comment by GerryDazoo** [comment]
FYI, that error you're seeing is caused when the Slingbox closes down the TCP control connection because it doesn't like something it received.

**Comment by Osymoko** [comment]
Thanks Gerry, definitely got a video signal , and I have tried different resolutions and bandwiths.  My video source is a satellite set-top box that inputs into the SB350 at 720p via component but I have also tested at 1080i as well -  I have also tried composite at VGA but no change in error messages.

Happy to test anything you throw my way, but otherwise enjoy your time away and good luck! Gary

**Comment by Osymoko** [comment]
(should have added that there was no change in the error messages )

**Comment by GerryDazoo** [comment]
OK, here's the deal. I had put in a huge hack to work around the fact that I couldn't figure out how to unwind the piece of perl code that figured out the proper encryption key to use after you got logged into the box. Apparently this code ONLY works with my box. So it might be awhile before I can get this sorted out with a general purpose solution. 
Can you run some perl on your PC? I might be able to send you a small perl script to regenerate the "keys.dat" file for your box.

**Comment by Osymoko** [comment]
Thanks Gerry, can't believe what kind efforts you are putting in. I will certainly take a look but sadly code changes and perl scripts are likely beyond me as I am not much of a coder at all. I will of course always happily test anything you can send our way.

**Comment by GerryDazoo** [comment]
OK, I'm going to make a small change to the code that will give me the info I need to make an encryption key file that is unique for your box. This should get you on the air. Standby, it might be later today or tomorrow, I;ll let you know when it's ready.

**Comment by GerryDazoo** [comment]
OK, check out the latest slingbox_server.py. When you run it it will still fail but please send me the line that says
CHALLANGE followed by 16 hex bytes
CHALLANGE c631844cf70531865d73650a16a0a536

**Comment by Osymoko** [comment]
Very happy to help , 
so the line is :

CHALLENGE 1bee68a294125b3ff55335ac5648580f

![image](https://user-images.githubusercontent.com/108595850/178326479-99be6421-fb70-432f-86aa-c2425195518c.png)

good luck!

**Comment by GerryDazoo** [comment]
[newkeys.zip](https://github.com/GerryDazoo/Slinger/files/9087125/newkeys.zip)

Unzip this and rename it to keys.dat in the same folder as the code. Take it out for a spin

**Comment by Osymoko** [comment]
I am truly astonished! thank you so much - speechless.

![image](https://user-images.githubusercontent.com/108595850/178354003-8e763932-9fcf-4f58-a1bb-89a7bab270d0.png)

(nb: This is workong on internal wifi  - there is no external IPv4 access even though port 8080 is open - is that what you'd expect?)

**Comment by Osymoko** [comment]
I changed the port forwarding rules and it now works perfectly externally. Its an absolute wonder!

**Comment by GerryDazoo** [comment]
Sure, that would be OK. I'm in the middle of porting the code for the older sling boxes. 
A little FYI, because you've got an open port on your firewall you will  be getting port scanned by hackers on a regular basis. There's code in the server to try to detect that and shutdown any bogus connection attempts. What I have found is the port scans don't usually try the higher port numbers but mostly some of the well know port numbers, 8080 for example. So on my router I mapped port 65432 to internal port 8080 and the number of hacking attempts reported by the server went down by 90% ish. I don't have an exact number but it was significant.

**Comment by Osymoko** [comment]
Yes, I noted the amount of hacking attempts and was very suprised. Will follow your advice. Its just amazing work.

**Comment by DoogieHowitzerWMD** [comment]
Came across this from @Osymoko cross-post on Reddit.

@GerryDazoo Thank you for your efforts, as this looks quite promising. I like that it's using the existing hardware (a slingbox 500), as that would be preferable to dropping about $250 on an HD encoder, which is a solution I've seen being discussed on Reddit.

I have more than a few questions on the workings of this, but I'll start with just one for now that builds upon the discussion track here in this issue thread.

> A little FYI, because you've got an open port on your firewall you will be getting port scanned by hackers on a regular basis.

Would setting up a VPN server improve the vulnerability of having the open ports? For instance, if I were using my Slingbox 500 and running the Sling Webserver on a Raspberry Pi, do you think it would be feasible to also set up this Raspberry Pi as a VPN client while using a _second_ Raspberry Pi as a VPN server, and then accessing the stream on a third device external to the network via that VPN?

A VPN is also going to require ports opened on the router in order to operate (could be wrong, but I'm pretty sure... I only really know enough coding and networking to get me in trouble), but perhaps that would be a more secure option as far as protecting our local networks?

**Comment by GerryDazoo** [comment]
Did you not already have a port open on your router for the slingbox? So I think you're not any worse off, especially if you use a high port number like I recommended. So it depends on how secure you want to be, Yes you'll need to open a port on your router to allow a VPN connection from the Internet to get to the server (I've been using openVPN ) 
There's no reason why you can't run my slingbox_server code on the same Pi that has the VPN server running. I don't see a need for an extra hop and a second Pi. This configuration works for me. I didn't bother to document this possible network configuration, most people will have their hands full just getting Python up and running.

**Comment by DoogieHowitzerWMD** [comment]
Hey GerryDazoo, thank you for the quick response.

>Did you not already have a port open on your router for the slingbox? So I think you're not any worse off, especially if you use a high port number like I recommended. So it depends on how secure you want to be, Yes you'll need to open a port on your router to allow a VPN connection from the Internet to get to the server (I've been using openVPN )

I originally set it up about 10 years ago, back when I was a kid who knew less about these sorts of things lol. I never had any problems, so I never revisited the configuration. Maybe I did open the port for it, but I don't specifically remember doing so. I figured I would want to improve upon the current approach while I'm having to retinker with things now, which would include adding a VPN in the mix.

> There's no reason why you can't run my slingbox_server code on the same Pi that has the VPN server running. I don't see a need for an extra hop and a second Pi.

That's good to know. My concern is that I actually have two slingboxes at the same house I'm looking to reconfigure/replace, as well add some NAS options (my wife puts old pictures to Facebook when she wants to free up space on her iCloud, and I have to offer her some sort of safer and easy-to-use alternative to doing that). For that reason, my mind was already thinking about needing a Pi as a dedicated VPN server with multiple Pi's being in the mix, but maybe I'll have the VPN and a slingplayer run on one and use one less Pi than I figured I was gonna need.

**Comment by GerryDazoo** [comment]
doogie:
The current software does not support more than one slingbox out of the box. You would need to copy all the files into a separate folder so you can have unique config.ini and keys.dat files. Also you would need to change the port the server is listening on to avoid a collision. What kind of NAS are you think about. I have a VPN server and Slingbox server running on my Synology box.

**Comment by DoogieHowitzerWMD** [comment]
I have a couple Pi model 2 B's sitting around, so when I'm able to get around to trying this out, I'll set one of those up to run but instances of the sling server and a VPN server as well. I'll report back whether I'm successful or if I encounter problems.

I have both slingboxes hardwired, so I'll just keep that setup as is and then plug the Pi in at the main router.
